"""first migration

Revision ID: e8c7ac72bf3f
Revises:
Create Date: 2026-09-01 22:50:49.691535

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8c7ac72bf3f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False, comment="Category ID"),
        sa.Column("name", sa.String(), nullable=False, comment="Category name"),
        sa.Column("parent_id", sa.Integer(), nullable=True, comment="Parent category ID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Creation timestamp"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Last update timestamp"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="Deletion timestamp"),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "suppliers",
        sa.Column("id", sa.Integer(), nullable=False, comment="Supplier ID"),
        sa.Column("name", sa.String(), nullable=False, comment="Supplier name"),
        sa.Column("contact_email", sa.String(), nullable=False, comment="Supplier contact email"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Creation timestamp"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Last update timestamp"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="Deletion timestamp"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact_email"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False, comment="User ID"),
        sa.Column("username", sa.String(), nullable=False, comment="Username"),
        sa.Column("email", sa.String(), nullable=False, comment="User email"),
        sa.Column("hashed_password", sa.String(), nullable=False, comment="Password hash"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Is user active"),
        sa.Column(
            "role", sa.Enum("OWNER", "STAFF", name="userrole"), nullable=False, comment="User role"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Creation timestamp"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Last update timestamp"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="Deletion timestamp"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False, comment="Order ID"),
        sa.Column("status", sa.String(), nullable=False, comment="Order status"),
        sa.Column(
            "created_by", sa.Integer(), nullable=False, comment="User ID who created the order"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Creation timestamp"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Last update timestamp"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="Deletion timestamp"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False, comment="Product ID"),
        sa.Column("sku", sa.String(), nullable=False, comment="Product SKU"),
        sa.Column("name", sa.String(), nullable=False, comment="Product name"),
        sa.Column("category_id", sa.Integer(), nullable=False, comment="Category ID"),
        sa.Column("price_cents", sa.Integer(), nullable=False, comment="Product price in cents"),
        sa.Column("current_stock", sa.Integer(), nullable=False, comment="Current stock quantity"),
        sa.Column("reorder_level", sa.Integer(), nullable=False, comment="Reorder level quantity"),
        sa.Column("supplier_id", sa.Integer(), nullable=False, comment="Supplier ID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Creation timestamp"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Last update timestamp"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="Deletion timestamp"),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku"),
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False, comment="Order Item ID"),
        sa.Column("order_id", sa.Integer(), nullable=False, comment="Order ID"),
        sa.Column("product_id", sa.Integer(), nullable=False, comment="Product ID"),
        sa.Column(
            "quantity", sa.Integer(), nullable=False, comment="Quantity of the product in the order"
        ),
        sa.Column(
            "unit_price_cents",
            sa.Integer(),
            nullable=False,
            comment="Unit price of the product in cents",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Creation timestamp"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Last update timestamp"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="Deletion timestamp"),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.Integer(), nullable=False, comment="Stock Movement ID"),
        sa.Column("product_id", sa.Integer(), nullable=False, comment="Product ID"),
        sa.Column("delta", sa.Integer(), nullable=False, comment="Change in stock quantity"),
        sa.Column(
            "movement_type",
            sa.String(),
            nullable=False,
            comment="Type of stock movement (e.g., 'in', 'out')",
        ),
        sa.Column(
            "created_by",
            sa.Integer(),
            nullable=False,
            comment="User ID who created the stock movement",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Creation timestamp"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Last update timestamp"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="Deletion timestamp"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stock_movements")
    op.drop_table("order_items")
    op.drop_table("products")
    op.drop_table("orders")
    op.drop_table("users")
    op.drop_table("suppliers")
    op.drop_table("categories")
    # ### end Alembic commands ###
